### ISSUE TITLE
Documentation of the information in the file output

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/openmkm#31]
Please provide a description in the documentation of the information in the file output in a sensitivity analysis that contains “_state” in the filename.

**Comment by MaxRCohen** [comment]
Hi @mbkumar, my mistake on this one. I should have included the word "BLANK" in the documentation for this to notify you that it needed your attention. Could you please fill this in when you have a chance? Right now, the documentation reads "Please fill this in, it is not the same information as in rctr_state_ss from the files I saw."

**Comment by mbkumar** [comment]
Done. rctr_state_ss file prints different quantities for 1d (PFR) and 0d (batch, CSTR) reactors. The same is the case for FIM run.
