### ISSUE TITLE
FIM_Diag value the Fischer information matrix 

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/openmkm#32]
For the FIM run, is the FIM_Diag value the Fischer information matrix diagonal value of the relevant reaction? If not, please correct the documentation.

**Comment by mbkumar** [comment]
Hello Gerhard,

Which part of the documentation this belongs to? I am guessing output, but I dont' see any section for sensitivity analysis.

**Comment by wittregr** [comment]
I missed adding that section. Now added.

**Comment by MaxRCohen** [comment]
Hi @mbkumar, if this is correct, can you close this comment?
