### ISSUE TITLE
Fill in the necessary information in all underlined sections and words of “BLANK” in the documentation. 

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/openmkm#37]
Please fill in the necessary information in all underlined sections and words of “BLANK” in the documentation.

**Comment by MaxRCohen** [comment]
Hi @mbkumar, can we get an update on this? Once these sections are filled in, it might help us realize other knowledge gaps we need to fill in, so it would be great if we could get this soon. Thank you for the help!

**Comment by MaxRCohen** [comment]
Hi @mbkumar, checking in again, could we get this addressed? I hope I'm not pestering too much, but we'll need this to understand the results fully.

**Comment by mbkumar** [comment]
Sure.  Will get to this this weekend.

Bharat

**Comment by mbkumar** [comment]
@MaxRCohen,
The output section is updated with BLANKS replaced with units. Could you please check it out and let me know if you have comments? Otherwise, I'll close the issue.

**Comment by MaxRCohen** [comment]
Hi @mbkumar ,
Thank you. I will take a look at it over the next few days and get back to you.

**Comment by MaxRCohen** [comment]
Hi @mbkumar, I apologize this took me a bit longer to address than expected. I've reviewed all the BLANKs, and they all seem clear. I also went through and reviewed all remaining Github issues on the outputs documentation and added comments for your review. Thank you for addressing all these points and for the hard work in making this software an optimal tool!
