### ISSUE TITLE
rctr_state mass values

### ISSUE THREAD

**Issue by MaxRCohen** [VlachosGroup/openmkm#45]
Hi @mbkumar, we see you added "mass flow rate into the reactor (in kg/s), mass flow rate out of the reactor (kg/s), mass produced from the surface (in kg/s), net rate of change of mass (kg/s) in the reactor" to the output files documentation for the rctr_state output file. However, we do not see these values in our output file. Can you clarify when we should expect to see these values? Are they for an updated version of OpenMKM, or for specific reactors only?

**Comment by mbkumar** [comment]
I haven't recompiled the code on vaccines yet.  I'll do it today.

Bharat

**Comment by MaxRCohen** [comment]
Hi @mbkumar, no rush. Sorry if it seemed like it was a time sensitive situation. To clarify, should we expect to see these values for all reactors with the new version of the code? Again, no rush on this, just wanted to confirm for the documentation.

**Comment by mbkumar** [comment]
Yes.  They are in the new version. I tried compiling openmkm today on
caviness but some weird errors are popping up.  I emailed Jeff and
hopefully we will have a working version on Monday.

Bharat

**Comment by mbkumar** [comment]
The new version of openmkm is up and running on caviness.
