### ISSUE TITLE
Meaning of additional note in rctr_state file documentation

### ISSUE THREAD

**Issue by MaxRCohen** [VlachosGroup/openmkm#46]
Hi @mbkumar, can you clarify what the Note in the rctr_state file documentation means? It says "Note: Mass flow rate out of the reactor is printed as -ve value. Similarly, if mass produced from surface is -ve, it means surface absorbs more mass than the mass released." What does "-ve" mean? Thank you for the help.

**Comment by mbkumar** [comment]
Hello Max, Its a short form for negative. Thanks for catching this. I replaced those with 'negative'.
