### ISSUE TITLE
Gas phase reactions

### ISSUE THREAD

**Issue by francescalb** [VlachosGroup/openmkm#51]
It does not seem that gas phase reactions are implemented in omkm, although an example on such a reactor set up is given in the [examples:](https://github.com/VlachosGroup/openmkm/blob/master/examples/rctr_input_files/batch_gasonly.yaml) .

With pmutt I am able to write (cti and xml) files that include reactions that occur in the gas phase as well as on the surface. While it is an alternative to stick to pure cantera without openmkm for sole gas phase systems, this is not so easily achievable when I need both surface reactions and gas phase reactions. 

It might very well be that I am doing something wrong, so do you have an example on such usage?

The error is get when running OpenMKM is:

'''
Error raised in Cantera. Exiting...

***********************************************************************
CanteraError thrown by GasKinetics::addReaction:
Unknown reaction type specified: 20
***********************************************************************
'''
A first test was made by simply adding the direct formation of NH3 from N2 and H2 in the gas phase (in your openmkm example from pmutt) in addition to all the surface interactions.

I would be very grateful on some pointers on how to proceed here.

**Comment by francescalb** [comment]
Sure, 

I have uploaded  a thermo.xml file (renamed with .txt as github does not support .xml uploads). It has been generated with the openmkm example in pmutt, only with the change of adding a direct reaction between N2 and H2 to form NH3 in the gas phase (I know, not very likely to occur...), with a completely invented Ea and A. The error message is the same. 

[thermo.xml.txt](https://github.com/VlachosGroup/openmkm/files/7392382/thermo.xml.txt)

**Comment by skasiraj** [comment]
> Sure,
> 
> I have uploaded a thermo.xml file (renamed with .txt as github does not support .xml uploads). It has been generated with the openmkm example in pmutt, only with the change of adding a direct reaction between N2 and H2 to form NH3 in the gas phase (I know, not very likely to occur...), with a completely invented Ea and A. The error message is the same.
> 
> [thermo.xml.txt](https://github.com/VlachosGroup/openmkm/files/7392382/thermo.xml.txt)

Just remove the type="surface" for the reaction 14. Since this is not a surface reaction.
